.\" Code lines counter doc 
.\" Copyright Łukasz Gajerski (https://github.com/Ukasz09)
.TH code_lines_counter
.SH NAME
code_lines_counter \- Generate a summary report of written lines of code (and not only)   
.SH SYNOPSIS
.B code_lines_counter
.RB [ OPTIONS ]
.SH DESCRIPTION
.B code_lines_counter
is a simple tool used to generate report about written lines of code for given directory, with all sub-directories 
.SH REMARKS
Line counter exclude all stuff described in
.B .gitignore 
files inside processed directory. In case of excluding files that you don't want to take into account during the counting, you need to add it to this .gitignore files or you can just add excludeed localizations by using
files inside searched directory. By adding this file to viewed directory you can easly exclude files that you don't want to take into account during the counting
If you want to exclude extra files without changing .gitignore files inside searched directories, you can easily to this by OPTION
.B \-\-add-ignored
.SH OPTIONS
.TP
.BI "\-a, \-\-add-lang " [LANG_NAME] " " [LANG_EXTENSION_1] " " <LANG_EXTENSION_2> " " ... 

Add new extension / extensions with corresponding language_name to config file
.TP
.BI "\-r, \-\-remove-lang " [LANG_NAME] " " [LANG_EXTENSION_1] " " <LANG_EXTENSION_2> " " ...

Remove extension / extensions with assigned language_name from config file.
.TP
.B \-l, \-\-list

Print all saved languages with assigned extensions, from config file 
.TP
.BI "\-d, \-\-dir " [DIRECTORY_PATH] 

Print report with lines of code for given directory with all sub-directories   
.TP
.B \-h, \-\-help

Display this man page
.TP
.BI "\-\-add-ignored " [LOCALIZATION_/_FILE] " " <LOCALIZATION_/_FILE> " " ... 

Add excludeed files / directories from counting process
.B code_lines_counter

(Take into consideration that
.B code_lines_counter
automatically exclude all files / localizations from .gitignore files inside searched directory !)
.TP
.BI "\-\-remove-ignored " [LOCALIZATION_/_FILE] " " <LOCALIZATION_/_FILE> " " ... 

Readd excludeed files / directories from counting process
.B code_lines_counter 

(Take into consideration that
.B code_lines_counter
automatically exclude all files / localizations from .gitignore files inside searched directory !)
.TP
.B "\-\-show-ignored  

Show all extra ignored files / directories 

(Take into consideration that
.B code_lines_counter
automatically exclude all files / localizations from .gitignore files inside searched directory !)
.TP
.BI "\-\-add-single-comment "[LANG_NAME] " " [COMMENT_SIGN]

Add \ change existed single comment sign for given language
.TP
.BI "\-\-remove-single-comment "[LANG_NAME]

Remove existed single comment sign for given language
.TP
.BI "\-\-add-multiple-comment " [LANG_NAME] " " [COMMENT_START_SIGN] " " [COMMENT_END_SIGN]

Add \ change existed multiple (block) comment signs for given language
.TP
.BI "\-\-remove-multiple-comment " [LANG_NAME]

Remove existed multiple (block) comment sign for given language
.TP
.B "\-\-show-comments-list

Show all saved comments signs (single and multiple)

.SH COPYRIGHT
MIT LICENCE, Łukasz Gajerski (https://github.com/Ukasz09)
